// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/code.go

// Package reposvcmocks is a generated GoMock package.
package reposvcmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCodeRepositoryInterface is a mock of CodeRepositoryInterface interface.
type MockCodeRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCodeRepositoryInterfaceMockRecorder
}

// MockCodeRepositoryInterfaceMockRecorder is the mock recorder for MockCodeRepositoryInterface.
type MockCodeRepositoryInterfaceMockRecorder struct {
	mock *MockCodeRepositoryInterface
}

// NewMockCodeRepositoryInterface creates a new mock instance.
func NewMockCodeRepositoryInterface(ctrl *gomock.Controller) *MockCodeRepositoryInterface {
	mock := &MockCodeRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockCodeRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCodeRepositoryInterface) EXPECT() *MockCodeRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Store mocks base method.
func (m *MockCodeRepositoryInterface) Store(ctx context.Context, biz, phone, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, biz, phone, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockCodeRepositoryInterfaceMockRecorder) Store(ctx, biz, phone, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockCodeRepositoryInterface)(nil).Store), ctx, biz, phone, code)
}

// Verify mocks base method.
func (m *MockCodeRepositoryInterface) Verify(ctx context.Context, biz, phone, code string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", ctx, biz, phone, code)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verify indicates an expected call of Verify.
func (mr *MockCodeRepositoryInterfaceMockRecorder) Verify(ctx, biz, phone, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockCodeRepositoryInterface)(nil).Verify), ctx, biz, phone, code)
}
