apiVersion: v1
# 这个指的是 我 k8s 有哪些 volume
#  我 k8s 有什么？？？？
kind: PersistentVolume
metadata:
  name: my-local-pv-v1
spec:
  storageClassName: suibianv1
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    #mac电脑特性 docker run --pid=host --privileged -it --rm justincormack/nsenter1
    path: "/mnt/live"

  