apiVersion: apps/v1
kind: Deployment
metadata:
  name: webook-mysql
  labels:
    app: webook-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webook-mysql
  template:
    metadata:
      name: webook-mysql
      labels:
        app: webook-mysql
    spec:
      containers:
        - name: webook-mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          imagePullPolicy: IfNotPresent #镜像来源
          volumeMounts:
#            - 这边要对应到 mysql 的数据存储的位置
#            - 通过 MySQL 的配置可以改这个目录
            - mountPath: /var/lib/mysql
#              我 POD 里面有那么多 volumes，我要用哪个
              name: mysql-storage
          ports:
            - containerPort: 3306
#        - name: webook-live-hadoop
      restartPolicy: Always
#      我整个 POD 有哪些
      volumes:
        - name: mysql-storage   #和上面的volumeMounts - name 匹配
          persistentVolumeClaim:
            claimName: webook-mysql-claim-v1
#        - name: hadoop-storage #分布式hadoop
#          persistentVolumeClaim:
#            claimName: webook-hadoop-claim-v1

      